### ISSUE TITLE
TypeError: function takes at most 2 arguments (3 given) when using with magneto

### ISSUE THREAD

**Issue by BTopbas** [i96751414/plugin.video.torrest#3]
```
ERROR <general>: [plugin.video.torrest] Caught exception:
                                                   Traceback (most recent call last):
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/plugin.video.torrest/lib/navigation.py", line 360, in run
                                                       plugin.run()
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/plugin.video.torrest/lib/navigation.py", line 37, in wrapper
                                                       raise e
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/plugin.video.torrest/lib/navigation.py", line 31, in wrapper
                                                       func(*args, **kwargs)
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/plugin.video.torrest/lib/navigation.py", line 81, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/plugin.video.torrest/lib/navigation.py", line 231, in play_magnet
                                                       play_info_hash(info_hash, buffer=buffer)
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/plugin.video.torrest/lib/navigation.py", line 37, in wrapper
                                                       raise e
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/plugin.video.torrest/lib/navigation.py", line 31, in wrapper
                                                       func(*args, **kwargs)
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/plugin.video.torrest/lib/navigation.py", line 271, in play_info_hash
                                                       buffer_and_play(info_hash, chosen_file.id)
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/plugin.video.torrest/lib/navigation.py", line 37, in wrapper
                                                       raise e
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/plugin.video.torrest/lib/navigation.py", line 31, in wrapper
                                                       func(*args, **kwargs)
                                                     File "/private/var/mobile/Containers/Data/Application/CFF0B279-F2D8-4F4D-A516-F538BE664656/Library/Caches/Kodi/addons/plugin.video.torrest/lib/navigation.py", line 304, in buffer_and_play
                                                       sizeof_fmt(total_done), translate(30244), sizeof_fmt(status.buffering_total), sizeof_fmt(speed)))
                                                   TypeError: function takes at most 2 arguments (3 given)
```

**Comment by i96751414** [comment]
Oh... I see what is the problem. I think xbmcgui is different on python3. I will fix this in a few minutes
