### ISSUE TITLE
Add-on does not  uninstall properly

### ISSUE THREAD

**Issue by lopezvg** [i96751414/plugin.video.torrest#7]
On uninstalling Torrest add-on in W10 it does not stop properly the Service, so Kodi cannot deleted the add-on's folder because there are some files in use (binary?):

```
2021-01-26 11:56:33.138 T:26392   ERROR: XFILE::CFile::Rename - Error renaming file C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.video.torrest
2021-01-26 11:56:33.138 T:26392   ERROR: Failed to move old addon files from 'C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.video.torrest' to 'C:\Users\xxx\AppData\Roaming\Kodi\addons\temp\4466f551-7973-41b4-8fa7-c777c64d86d5'
2021-01-26 11:56:33.138 T:26392   ERROR: CAddonUnInstallJob[plugin.video.torrest]: could not delete addon data.
```
As a consequence, if the Torrest add-on is reinstalled without Kodi re-init , it gives the following error:

```
2021-01-26 11:59:26.416 T:17476   ERROR: XFILE::CFile::Rename - Error renaming file C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.video.torrest
2021-01-26 11:59:26.416 T:17476   ERROR: Failed to move old addon files from 'C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.video.torrest' to 'C:\Users\xxx\AppData\Roaming\Kodi\addons\temp\f04e79b0-e35a-43f1-81e2-2d66dd32bd7d'
```

**Comment by i96751414** [comment]
Thanks a lot for reporting this. I was able to reproduce it. Can you tell if this happens with other addons running background services? (for instance quasar).

The problem is in fact that Kodi is not stopping the service before trying to uninstall the addon, which is problematic.

As a workaround you can manually stop the service by changing the settings. This needs further investigation to understand if it is a Kodi issue or a Torrest issue (most likely).

**Comment by lopezvg** [comment]
It works fine with Quasar.

I think the problem might be in the service.handle_crashes function.  I think you have to use "if monitor.waitForAbort(xxx):"

See this example form the Kodi documentation:

    ```
    monitor = xbmc.Monitor()
    while not monitor.abortRequested():
        # Sleep/wait for abort for 10 seconds
        if monitor.waitForAbort(10):
            # Abort was requested while waiting. We should exit
            break
        xbmc.log("hello addon! %s" % time.time(), level=xbmc.LOGNOTICE)
```

**Comment by i96751414** [comment]
Unfortunately it's not that.. However, I have an idea why this is happening :) I thought it was not necessary to copy the binary to a different folder and we would be able to run it directly from the addon folder. It seems I was wrong.
I'll fix it later today.

**Comment by lopezvg** [comment]
It works nearly fine, but not quite.  I dumped the master.zip over the installed add-on to try with the latest corrections.

It kills the Torrest process, deletes the add-on folder, but does not deletes the userdata folder.  On attempting to delete it manually, it shows that the Torrens.log file is still open.

As an aside problem, I do not know if directly related to this, on starting Kodi, Torrest gives messages for several cancellations of the service.  See the error. I have introduced a couple of xbmc.log in services.py for further clarification:

```
2021-01-27 13:03:06.408 T:2204   ERROR: http://127.0.0.1:61235/settings/get get
2021-01-27 13:03:06.412 T:2204   ERROR: http://127.0.0.1:61235/settings/set post
2021-01-27 13:03:06.412 T:2204   ERROR: json{'download_path': 'E:\\Peliculas\\Kodi\\Alfa\\downloads\\Torrest', 'session_save': 30, 'disable_lsd': False, 'seed_time_ratio_limit': 0, 'listen_port': 6889, 'listen_interfaces': '', 'max_download_rate': 0, 'active_limit': 500, 'max_upload_rate': 900000, 'share_ratio_limit': 0, 'active_checking_limit': 1, 'disable_upnp': False, 'alerts_log_level': 0, 'service_log_level': 4, 'tuned_storage': True, 'encryption_policy': 0, 'disable_dht': False, 'proxy': {'username': '', 'password': '', 'hostname': '', 'type': 0, 'port': 1080}, 'torrents_path': 'E:\\Peliculas\\Kodi\\Alfa\\downloads\\Torrest\\Torrents', 'buffer_size': 20971520, 'active_downloads_limit': 3, 'active_seeds_limit': 5, 'active_lsd_limit': 60, 'disable_natpmp': False, 'active_dht_limit': 88, 'connections_limit': 0, 'piece_wait_timeout': 60, 'outgoing_interfaces': '', 'user_agent': 0, 'seed_time_limit': 0, 'limit_after_buffering': False, 'active_tracker_limit': 1600}
2021-01-27 13:03:06.421 T:4296 WARNING: Repository add-on repository.github uses plain HTTP for add-on downloads in path http://127.0.0.1:61234/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2021-01-27 13:03:07.422 T:2204 WARNING: Previous line repeats 36 times.
2021-01-27 13:03:07.422 T:2204   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ConnectionError'>
                                            Error Contents: ('Connection aborted.', error(10054, 'Se ha forzado la interrupci\xf3n de una conexi\xf3n existente por el host remoto'))
                                            Traceback (most recent call last):
                                              File "C:\Users\lopez\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\service.py", line 129, in onSettingsChanged
                                                self._update_daemon_settings()
                                              File "C:\Users\lopez\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\service.py", line 102, in _update_daemon_settings
                                                r = self._request("post", self._settings_set_uri, json=kodi_settings)
                                              File "C:\Users\lopez\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\service.py", line 59, in _request
                                                return requests.request(method, "http://127.0.0.1:{}/{}".format(self._port, url), **kwargs)
                                              File "C:\Users\lopez\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "C:\Users\lopez\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 533, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "C:\Users\lopez\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "C:\Users\lopez\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 498, in send
                                                raise ConnectionError(err, request=request)
                                            ConnectionError: ('Connection aborted.', error(10054, 'Se ha forzado la interrupci\xf3n de una conexi\xf3n existente por el host remoto'))
                                            -->End of Python script error report<--
```

**Comment by i96751414** [comment]
Regarding the userdata, that's expected. It's a kodi problem, which does not terminate the service before uninstalling the addon (that's why we have to copy the daemon to userdata and run it from there). I'm afraid there's nothing we can do here.

Regarding the last problem, I believe you are mentioning the last exception, right? If so, I believe that will be addressed on the next release (this was a race condition on the daemon and not the python service). To confirm that, you can check the userdata/plugin.video.torrest/torrest.log when this error happens.

**Comment by lopezvg** [comment]
> Regarding the userdata, that's expected. It's a kodi problem, which does not terminate the service before uninstalling the addon (that's why we have to copy the daemon to userdata and run it from there). I'm afraid there's nothing we can do here.
Ok

> Regarding the last problem, I believe you are mentioning the last exception, right? If so, I believe that will be addressed on the next release (this was a race condition on the daemon and not the python service). To confirm that, you can check the userdata/plugin.video.torrest/torrest.log when this error happens.

Actually the whole set is related.  Line 2 provokes the error using the json in line 3.  This Exception repeats 4 times.  Attached the Torrest.log while the errors are happening, but after the last error the log is reseted to the initial state with only this line left; [GIN] 2021/01/27 - 16:27:41 | 404 |            0s |       127.0.0.1 | GET      "/"

```
INFO  main         - main             Loading configs
INFO  main         - main             Starting bittorrent service
INFO  bittorrent   - configure        Applying session settings...
INFO  bittorrent   - configure        UserAgent: torrest/0.0.6 libtorrent/1.2.11.0
INFO  main         - main             Starting torrent daemon on port 61235
[GIN] 2021/01/27 - 16:27:41 | 404 |            0s |       127.0.0.1 | GET      "/"
[GIN] 2021/01/27 - 16:27:42 | 200 |         131µs |       127.0.0.1 | GET      "/settings/get"
INFO  bittorrent   - configure        Applying session settings...
INFO  bittorrent   - configure        UserAgent: torrest/0.0.6 libtorrent/1.2.11.0
[GIN] 2021/01/27 - 16:27:42 | 200 |    447.3575ms |       127.0.0.1 | POST     "/settings/set"
[GIN] 2021/01/27 - 16:27:42 | 200 |            0s |       127.0.0.1 | GET      "/settings/get"
```

You mention that this will be addressed in the next release, but I think that I am using the "next release" for the testing, as I am updating the installed version 0.0.9 with the latest code from Github master_code.zip.  This problem does to occur with the standard version 0.0.9

**Comment by lopezvg** [comment]
I checked again Torrest.log and shows the following, although there is no apparent activity in Kodi:

```
INFO  main         - main             Loading configs
INFO  main         - main             Starting bittorrent service
INFO  bittorrent   - configure        Applying session settings...
INFO  bittorrent   - configure        UserAgent: torrest/0.0.6 libtorrent/1.2.11.0
INFO  main         - main             Starting torrent daemon on port 61235
[GIN] 2021/01/27 - 16:27:48 | 404 |            0s |       127.0.0.1 | GET      "/"
[GIN] 2021/01/27 - 16:29:39 | 200 |            0s |       127.0.0.1 | GET      "/settings/get"
INFO  bittorrent   - configure        Applying session settings...
INFO  bittorrent   - configure        UserAgent: torrest/0.0.6 libtorrent/1.2.11.0
[GIN] 2021/01/27 - 16:29:39 | 200 |    260.4604ms |       127.0.0.1 | POST     "/settings/set"
[GIN] 2021/01/27 - 16:29:39 | 200 |            0s |       127.0.0.1 | GET      "/settings/get"
INFO  bittorrent   - configure        Applying session settings...
INFO  bittorrent   - configure        UserAgent: torrest/0.0.6 libtorrent/1.2.11.0
[GIN] 2021/01/27 - 16:29:39 | 200 |    521.8654ms |       127.0.0.1 | POST     "/settings/set"
[GIN] 2021/01/27 - 16:31:39 | 200 |            0s |       127.0.0.1 | GET      "/settings/get"
INFO  bittorrent   - configure        Applying session settings...
INFO  bittorrent   - configure        UserAgent: torrest/0.0.6 libtorrent/1.2.11.0
[GIN] 2021/01/27 - 16:31:39 | 200 |    439.2018ms |       127.0.0.1 | POST     "/settings/set"
[GIN] 2021/01/27 - 16:31:39 | 200 |      1.0018ms |       127.0.0.1 | GET      "/settings/get"
INFO  bittorrent   - configure        Applying session settings...
INFO  bittorrent   - configure        UserAgent: torrest/0.0.6 libtorrent/1.2.11.0
[GIN] 2021/01/27 - 16:31:40 | 200 |    531.9287ms |       127.0.0.1 | POST     "/settings/set"
[GIN] 2021/01/27 - 16:33:39 | 200 |            0s |       127.0.0.1 | GET      "/settings/get"
INFO  bittorrent   - configure        Applying session settings...
INFO  bittorrent   - configure        UserAgent: torrest/0.0.6 libtorrent/1.2.11.0
[GIN] 2021/01/27 - 16:33:39 | 200 |    167.9056ms |       127.0.0.1 | POST     "/settings/set"
[GIN] 2021/01/27 - 16:33:39 | 200 |            0s |       127.0.0.1 | GET      "/settings/get"
INFO  bittorrent   - configure        Applying session settings...
INFO  bittorrent   - configure        UserAgent: torrest/0.0.6 libtorrent/1.2.11.0
[GIN] 2021/01/27 - 16:33:40 | 200 |     522.884ms |       127.0.0.1 | POST     "/settings/set"
[GIN] 2021/01/27 - 16:35:39 | 200 |            0s |       127.0.0.1 | GET      "/settings/get"
INFO  bittorrent   - configure        Applying session settings...
INFO  bittorrent   - configure        UserAgent: torrest/0.0.6 libtorrent/1.2.11.0
[GIN] 2021/01/27 - 16:35:39 | 200 |    251.9016ms |       127.0.0.1 | POST     "/settings/set"
[GIN] 2021/01/27 - 16:35:39 | 200 |            0s |       127.0.0.1 | GET      "/settings/get"
```

**Comment by i96751414** [comment]
When I say next release I mean Torrest's next release (https://github.com/i96751414/torrest), which will be 0.0.7.
plugin.video.torrest uses the binary from torrest (standalone) project as a dependency. 
Their versions are not related - currently plugin.video.torrest is at 0.0.9 and torrest is at 0.0.6.

You're correct. The issue you are seeing happens precisely because the code on master is supposed to work with torrest 0.0.7 (not released yet).

**Comment by i96751414** [comment]
Out of curiosity, where you changing any settings? Looking at those logs it looks like something is changing settings every 2 minutes. If so, I advice not to do that.. As that means restarting the service every 2 minutes to apply the new settings.

**Comment by lopezvg** [comment]
> Out of curiosity, where you changing any settings? Looking at those logs it looks like something is changing settings every 2 minutes. If so, I advice not to do that.. As that means restarting the service every 2 minutes to apply the new settings.

That was my point.  I check for some settings every two minutes, but I'm not changing any.  With version 0.0.9 I see in the Torrest.log only "/settings/get" and no "/settings/set",  Probably it is a mismatch between the newer Python code and the standard Torrest 0.0.6 version
