### ISSUE TITLE
Torrest deamon not initialized, most probably due to a "&" in the Torrest add-on path

### ISSUE THREAD

**Issue by lopezvg** [i96751414/plugin.video.torrest#8]
`2021-03-09 16:10:13.765 T:9228  NOTICE: [plugin.video.torrest] Daemon not found. Aborting service...
2021-03-09 16:10:20.790 T:8756   ERROR: [plugin.video.torrest] Failed to update background progress
repeats 3 more times
2021-03-09 16:10:48.287 T:7920   ERROR: [plugin.video.torrest] Caught exception:
                                            Traceback (most recent call last):
                                              File "C:\Users\Tere&Luis\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 435, in run
                                                plugin.run()
                                              File "C:\Users\Tere&Luis\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "C:\Users\Tere&Luis\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "C:\Users\Tere&Luis\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 52, in wrapper
                                                raise e
                                            IOError: [Errno 2] No such file or directory: u'C:/Users/Tere'`

**Comment by i96751414** [comment]
I wasn't able to reproduce this, and I tested both Kodi 18/19. The '&' should not be a problem in the latest version.

I'll need more info to understand what's happening here. A full log would be appreciated.

**Comment by lopezvg** [comment]
No problem
[LOG885986347.log](https://github.com/i96751414/plugin.video.torrest/files/6116919/LOG885986347.log)

**Comment by i96751414** [comment]
Also, I've just remembered one thing, when calling 'play_path' route, the path must be url encoded.

**Comment by i96751414** [comment]
I'm closing this issue as I believe it is related with two external problems:

1. The user didn't have the correct add-on installed (containing the binary);
2. This was probably called from `plugin://plugin.video.torrest/play_path?path=<path>` and the `path` was not url encoded, so any & characters would break this.

**Comment by lopezvg** [comment]
You were right in both cases:

- The user did not have the correct binary: comparing the first log the user sent and the latest one is obvious that in the first case the user installed manually the wrong platform. Now usig the repo it went well.
- The problem in this case is that Torrest is providing nearly no information about this problem.  It only log "[plugin.video.torrest] Daemon not found. Aborting service...", which is difficult to find in the log and does not provide any help to address the problem.
- I propose that right before you call the binary, you state the full path from for "add-on/resources/bin/[platform]/torrest", so it is easy to  identify if there is a mismatch in the platform.  Additionally, if the call returns an error, please log another message with sufficient information to address the problem.

- Related to the encode, again right, by mistake I was decoding...
